services:
  - type: web
    name: sentiotrack
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('vader_lexicon')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: SentioTrack/0.1
    plan: free
